approvedGitRepositories:
    - '**'

enableConstraintsChecks: true

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 0

preferReuse: true

progressBarStyle: patrick
