import type {} from './Box.react-jsx'
import type {} from './Mesh.react-jsx'
import type {} from './MixedPlane.react-jsx'
import type {} from './Plane.react-jsx'
import type {} from './Points.react-jsx'
import type {} from './RoundedRectangle.react-jsx'
import type {} from './Shape.react-jsx'
import type {} from './Sphere.react-jsx'
